### ISSUE TITLE
Help Bubbles

### ISSUE THREAD

**Issue by Technickel-Dev** [Technickel-Dev/triangulation#2]
The tool needs explanation for those who don't know how to use it. Using ? popups would be a good way to hide that information but have it accessible

**Comment by ncnapier** [comment]
Hello,

I can add a tool-tip that will display the necessary information when the user hovers over the tool-tip. 

thanks

**Comment by Technickel-Dev** [comment]
That would be great!

**Comment by ncnapier** [comment]
Created pull requests. 

This my first time making contributions. Please let me know if there's another way I should have gone about the process. 

Please let me know of any improvements that I can make to the changes. 

The app is really cool! Good work!

**Comment by Technickel-Dev** [comment]
Hey! Sorry for the long wait, I really appreciate you putting in the work!

Just some tips for the future, usually when doing a feature, rather than open multiple pull requests for multiple changes as you did with one PR having the html and one having the CSS, you can commit both to the same branch. If you did everything through the Github UI, this is where you'd want to learn how to use an integrated development environment and the various git commands.

Another tip would be to integrate your changes into the app more, as you created a whole now app.html rather than using the existing one under src.

Overall, super small suggestions and that's why I already accepted the PRs, again really appreciate the work and hope you enjoy making more contributions to various projects in the future!
