### ISSUE TITLE
Restrict type up input file

### ISSUE THREAD

**Issue by Technickel-Dev** [Technickel-Dev/triangulation#7]
When using the image input button, it would be nice to restrict to using only image type files using [accept](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept)

**Comment by jaas666** [comment]
A note on accept..

> The accept attribute doesn't validate the types of the selected files; it provides hints for browsers to guide users towards selecting the correct file types. It is still possible (in most cases) for users to toggle an option in the file chooser that makes it possible to override this and select any file they wish, and then choose incorrect file types.

> Because of this, you should make sure that expected requirement is validated server-side

**Comment by Technickel-Dev** [comment]
I appreciate the reminder! However since everything is statically served on the client there is no server side to validate things. Correct me if I'm wrong, as I'm by no means a security expert, but since everything is running client side, we don't have to be concerned with incorrect files.

This feature is just a gentle nudge for the user to only be able to upload something that will work and to make it easier since it highlights the "accepted" files. If they choose to circumvent it for whatever reason, that's on them lol.

**Comment by jaas666** [comment]
Yeah.. just mentioning in case the goal was to disable upload of certain
files 👏

I guess the next question is, which file types you want to allow?

**Comment by Technickel-Dev** [comment]
I appreciate you keeping an eye out!

Good question, given I don't have any preference, I'd be happy with `image/*` and if there are problems down the line with a certain image format I figure out how to support that later
